name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build
      run: go build -o dummy-server.bin ./cmd 

    - name: Simple Test
      run: |
        ./dummy-server.bin &
        sleep 3
        curl -s http://localhost:8888
        kill $!
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: ./dummy-server.bin
